<?php

function view_ajax_node_init() {
  drupal_add_js('misc/jquery.form.js');
  drupal_add_library('system', 'drupal.ajax');
}

/**
 * Implements hook_menu().
 */
function view_ajax_node_menu() {
  // A menu callback is required when using ajax outside of the Form API.
  $items['ajax-view'] = array(
    'page callback' => 'ajax_link_response',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function ajax_link_response($type = 'ajax', $nid = 0, $action = 'append') {
  $output = _view_ajax_node_load_noder($nid);
  if ($type == 'ajax') {
    $commands = array();
    if($action == 'append') {
      $commands[] = ajax_command_append('.encyclopedia-entry-'.$nid, '<div id="content">' . $output . '</div>');
      $commands[] = ajax_command_invoke('.encyclopedia-entry-'.$nid.' .views-field-title a', 'attr', array('href', 'ajax-view/ajax/'.$nid.'/remove'));
    }
    else if($action == 'remove') {
      $commands[] = ajax_command_remove('.encyclopedia-entry-'.$nid . ' #content');
      $commands[] = ajax_command_invoke('.encyclopedia-entry-'.$nid.' .views-field-title a', 'attr', array('href', 'ajax-view/ajax/'.$nid));
    }
    $page = array(
      '#type' => 'ajax',
      '#commands' => $commands
    );
    ajax_deliver($page);
  }
  elseif ($nid > 0) {
    drupal_goto('node/' . $nid);
  }
  else {
    $output = '<div id="content">' . $output . '</div>';
    return $output;
  }
}

function _view_ajax_node_load_noder($nid = 0) {
  $node = node_load($nid, NULL, false);
  if ($node) {
    $vnode = node_view($node);
    return theme("node", $vnode);
  }
 // return views_embed_view ('front','page_1', $nid);
}
